### ISSUE TITLE
StdErr does not get populated with issue ssh command

### ISSUE THREAD

**Issue by ChrisAtkinson1** [ChrisPark89/zowe-cli#6]
It appears that only STDOUT gets populated on the response from issue ssh command.

I also have never seen the STATUS change from 0. 

Would expect this if the command fails badly on uss.

**Comment by ChrisPark89** [comment]
All the output from the ssh command is populated to STDOUT in the client side. This is how interactive shell is implemented in SSH2 module. (https://github.com/mscdex/ssh2/issues/758)

The reason we decided to go to interactive ssh command was because non-interactive ssh command does not run shell profile(e.g. ~/.profile) hence no environment variables set we need when it runs the command.

**Comment by matthewpwilson** [comment]
Look at the issue on ssh2 linked above it seems this is just how the SSH server works when using an interactive shell, so we'll have live with this as a limitation.

**Comment by ChrisAtkinson1** [comment]
Agreed - so we will only populate STDOUT and NOT STATUS and STDERR.

**Comment by ChrisPark89** [comment]
It still populates both STDOUT and STDERR, but it doesn't distinguish between them.

**Comment by ChrisPark89** [comment]
I'll close this issue because it's a ssh2 module limitation.
